version: '3.8'
services:
  example-server-1:
    build:
      context: .
    image: docker.io/markojerkic/example-server-1:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - DISCOVERY_CLIENT_DISCOVERY_SERVER_URL=http://host.docker.internal:8080
  example-server-1-2:
    image: docker.io/markojerkic/example-server-1:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - DISCOVERY_CLIENT_DISCOVERY_SERVER_URL=http://host.docker.internal:8080
