# fly.toml app configuration file generated for discovery-example-server-1 on 2024-12-31T14:24:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discovery-example-server-1'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  SERVER_PORT = 8080
  DISCOVERY_CLIENT_DISCOVERY_SERVER_URL = "https://discovery-server.fly.dev"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
