# fly.toml app configuration file generated for discovery-server on 2024-12-30T21:58:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discovery-server'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  SERVER_PORT = 8081
  SPRING_DATASOURCE_URL = "jdbc:sqlite:/litefs/discovery.db"


[[vm]]
  size = 'shared-cpu-4x'

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
