# fly.toml app configuration file generated for discovery-server on 2024-12-30T21:58:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discovery-server'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
