#!/usr/bin/env bash

# This script is used to build and deploy the application to Fly.io
./mvnw clean install -DskipTests

cd ./discovery-server
docker compose build
docker push docker.io/markojerkic/discovery-server

cd ../examples/example-server-1
docker build -t docker.io/markojerkic/example-server-1 .
docker push docker.io/markojerkic/example-server-1

ssh $DISCOVERY_SERVER_USER@$DISCOVERY_SERVER_HOST "docker ps"
