name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DISCOVERY_SERVER_HOST: ${{ secrets.DISCOVERY_SERVER_HOST }}
  DISCOVERY_SERVER_USER: ${{ secrets.DISCOVERY_SERVER_USER }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: ./custom-load-balancer
        run: ./mvnw clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        working-directory: ./custom-load-balancer
        run: |
          docker compose build
          docker compose push

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DISCOVERY_SERVER_HOST }}
          username: ${{ env.DISCOVERY_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/projects/projekt-d/discovery-server
            mkdir -p ~/projects/projekt-d/example-server-1

            cd ~/projects/projekt-d/discovery-server
            docker compose pull
            docker compose up -d --force-recreate

            cd ~/projects/projekt-d/example-server-1
            docker compose pull
            docker compose up -d --force-recreate

            docker image prune -f
